describe('Artist page user flow', () => {
  it('should see artist details, collaborator section, and be able to add and remove the artist from the collaborator form', () => {
    cy.fixture('coltraneArtistPage.json').as('coltraneArtistPage')
      .then((json) => {
        cy.intercept('GET', 'https://jazz-collaborations-api.herokuapp.com/api/v1/musicians/2', json)
      })
    cy.visit('http://localhost:3000/artist/2')
      .get('.collaborators-form')
      .get('.middle-button')
      .should('be.disabled')
      .get('#left')
      .should('be.disabled')
      .get('.artist-name')
      .contains('John Coltrane')
      .get('.instrument')
      .contains('Saxophone')
      .get('.add-collaborator-button').click()
      .get('.collaborator-left')
      .contains('John Coltrane')
      .get('.add-collaborator-button')
      .should('be.disabled')
      .get('.remove-button').eq(0).click()
      .get('.add-collaborator-button')
      .should('not.be.disabled')
      .get('.albums-container')
      .get('.album-link')
      .contains('Blue Train').click()
      .url().should('eq', 'http://localhost:3000/album/201')
  })
})